[package]
name = "agnostic-orderbook"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
no-entrypoint = []
test-bpf = []

[dependencies]


[dev-dependencies]


[lib]
crate-type = ["cdylib", "lib"]
